# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/common/error.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'v1/common/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15v1/common/error.proto\x12\x16\x63om.hearlers.v1.common\x1a\x19google/protobuf/any.proto\"a\n\x05\x45rror\x12\x16\n\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n\x04type\x18\x02 \x01(\tR\x04type\x12,\n\x06\x65rrors\x18\x03 \x03(\x0b\x32\x14.google.protobuf.AnyR\x06\x65rrorsB\xa4\x01\n\x1a\x63om.com.hearlers.v1.commonB\nErrorProtoP\x01\xa2\x02\x04\x43HVC\xaa\x02\x16\x43om.Hearlers.V1.Common\xca\x02\x16\x43om\\Hearlers\\V1\\Common\xe2\x02\"Com\\Hearlers\\V1\\Common\\GPBMetadata\xea\x02\x19\x43om::Hearlers::V1::Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.common.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.com.hearlers.v1.commonB\nErrorProtoP\001\242\002\004CHVC\252\002\026Com.Hearlers.V1.Common\312\002\026Com\\Hearlers\\V1\\Common\342\002\"Com\\Hearlers\\V1\\Common\\GPBMetadata\352\002\031Com::Hearlers::V1::Common'
  _globals['_ERROR']._serialized_start=76
  _globals['_ERROR']._serialized_end=173
# @@protoc_insertion_point(module_scope)
