# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/common/pagination.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'v1/common/pagination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v1.common import sort_order_pb2 as v1_dot_common_dot_sort__order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1av1/common/pagination.proto\x12\x16\x63om.hearlers.v1.common\x1a\x1av1/common/sort_order.proto\"z\n\nPagination\x12@\n\nsort_order\x18\x01 \x01(\x0e\x32!.com.hearlers.v1.common.SortOrderR\tsortOrder\x12\x14\n\x05since\x18\x02 \x01(\tR\x05since\x12\x14\n\x05limit\x18\x03 \x01(\x05R\x05limitB\xa9\x01\n\x1a\x63om.com.hearlers.v1.commonB\x0fPaginationProtoP\x01\xa2\x02\x04\x43HVC\xaa\x02\x16\x43om.Hearlers.V1.Common\xca\x02\x16\x43om\\Hearlers\\V1\\Common\xe2\x02\"Com\\Hearlers\\V1\\Common\\GPBMetadata\xea\x02\x19\x43om::Hearlers::V1::Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.common.pagination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.com.hearlers.v1.commonB\017PaginationProtoP\001\242\002\004CHVC\252\002\026Com.Hearlers.V1.Common\312\002\026Com\\Hearlers\\V1\\Common\342\002\"Com\\Hearlers\\V1\\Common\\GPBMetadata\352\002\031Com::Hearlers::V1::Common'
  _globals['_PAGINATION']._serialized_start=82
  _globals['_PAGINATION']._serialized_end=204
# @@protoc_insertion_point(module_scope)
