version: "3.8"

services:
  api_gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api_gateway
    ports:
      - "8000:8000"
    env_file:
      - ../.env.dev

  service_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.service_server
    ports:
      - "8001:8001"
    env_file:
      - ../.env.dev
